[workspace.package]
version = "0.5.0"
edition = "2024"
description = "High performance query engine for both offline compute and online serving"
authors = ["btnokami"]
repository = "https://github.com/SkardiLabs/skardi"
homepage = "https://github.com/SkardiLabs/skardi"
license = "Apache-2.0"

[workspace]
members = [ "crates/cli",
            "crates/skardi",
            "crates/server"]

resolver = "2"

[workspace.dependencies]
better-auth = { version = "0.9.0", default-features = false }
better-auth-diesel-sqlite = { version = "=0.1.2" }
anyhow = "1.0.98"
arrow = { version = "57.0.1", features = [
    "prettyprint",
    "chrono-tz",
] }
arrow-json = { version = "57.0.1" }
async-trait = "0.1.88"
axum = "0.7"
cookie = "0.18"
clickhouse = "0.14"
ctor = "0.4.1"
datafusion = { version = "52.1.0", default-features = false, features = [
    "nested_expressions",
    "datetime_expressions",
    "regex_expressions",
    "string_expressions",
    "unicode_expressions",
    "compression",
    "parquet",
    "recursive_protection",
    "sql",
] }
datafusion-common = { version = "52.1.0" }
datafusion-federation = "=0.5.1"
datafusion-table-providers = { version = "0.10.0", default-features = false, features = ["postgres", "mysql", "flight", "clickhouse"] }
tokio-rusqlite = { version = "0.7", features = ["bundled", "load_extension"] }
env_logger = "0.11"
futures = "0.3"
iceberg = "0.9.0"
iceberg-datafusion = "0.9.0"
iceberg-storage-opendal = "0.9.0"
insta = { version = "1.41.1", features = ["glob", "filters"] }
lance = { version = "4.0.0", default-features = false }
lance-index = { version = "4.0.0" }
lance-linalg = { version = "4.0.0" }
log = "0.4.27"
object_store = { version = "0.12.4", default-features = false, features = ["aws", "gcp", "azure", "http"] }
parking_lot = "0.12"
parquet = { version = "57.0.1", default-features = false, features = [
    "arrow",
    "async",
    "object_store",
] }
regex = "1.8"
rstest = "0.25.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "tls-rustls", "postgres"] }
tempfile = "3.23.0"
tokio = { version = "1.44.2", features = ["macros", "rt", "sync"] }
tower = "0.4"
tower-http = "0.5"
tracing = "0.1"
url = "2.5.4"
uuid = { version = "1.4", features = ["v4", "serde"] }

[profile.release]
lto = "thin"
codegen-units = 1
strip = true

[profile.release-cli]
inherits = "release"
lto = true
panic = "abort"

[workspace.lints.clippy]
# Detects large stack-allocated futures that may cause stack overflow crashes (see threshold in clippy.toml)
large_futures = "warn"
used_underscore_binding = "warn"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(tarpaulin)"] }
unused_qualifications = "deny"
